spring:
  data:
    mongodb:
      uri: mongodb+srv://{username}:{Passkey}@cluster0.b0e1k8t.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: shortU
      auto-index-creation: true

server:
  port: 8081








